### ISSUE TITLE
Support to Optifine and Forge

### ISSUE THREAD

**Issue by ghost** [ammarx/TagAPI_3#14]
Pls add forge and optifine

**Comment by kisman2000** [comment]
yes!

**Comment by joveaaron** [comment]
Hi friend, I am pleased to announce that I am making a fork of this code as it has not been updated in over 6 years. I'm porting it to C#, only Windows support for now, but making it work in Mac OS/Linux shouldn't be hard.

I am at around 7% total port in 2 days, I estimate half the code will be ported in approx 9 days. I am sure that by October, the code will be fully ported to C#.

I will reply to this issue when the port status reaches 100% for Windows and when Mac OS/Linux compatibility is reached.

So far I've only used the original repo's code and custom code to replicate the Apache commons methods being used. I expect licensing to not be a problem.

**Comment by ammarx** [comment]
Code updated to support up to version 1.21.1. Forge and Optifine support was never a priority for this project, hence, it was never fully added. 

@joveaaron Looking forward to your project :)
